branch-defaults:
  master:
    environment: Mynode-env
environment-defaults:
  Mynode-env:
    branch: null
    repository: null
global:
  application_name: mynode
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-east-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
