version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.8.0
      - image: postgres:9.6.10
        environment:
          POSTGRES_USER: node
          POSTGRES_PASSWORD: node
          POSTGRES_DB: node

    steps:
      - checkout

      - run: cd server && npm install

      - run: cd server && npm run test
  build:
    machine: true
    steps:
     - checkout

     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: docker build --build-arg DB_USER=$DB_USER  --build-arg DB_PASS=$DB_PASS --build-arg DB_HOST=$DB_HOST -p 1337:1337 -t filip505/mynode:latest ./server

     - run: docker push filip505/mynode:latest

     - run:
        name: Install pip
        command: |
          sudo apt update
          sudo apt install -y python-pip python-dev
          sudo pip install --upgrade setuptools

     - run:
        name: Install AWS dependencies
        command: |
         sudo pip install awsebcli

    # - run: eb init -p docker mynode
      
     - run: eb deploy Mynode-env

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build