version: 2
jobs:
  build:
    docker:
      - image: postgres:9.6.5
        environment:
          POSTGRES_USER: node
          POSTGRES_DB: node
          POSTGRES_PASSWORD: node

    steps:
      - checkout

      - run: apt-get update && sudo apt-get install curl

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: docker build -t mynode -f ./server/Dockerfile.dev .

      - run: docker run test


