version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.8.0
      - image: postgres:9.6.10
        environment:
          POSTGRES_USER: node
          POSTGRES_PASSWORD: node
          POSTGRES_DB: node

    steps:
      - checkout

      - run: cd server && npm install

      - run: cd server && npm run test
  build:
    machine: true
    steps:
     - checkout

     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: echo $DB_USER

     - run: docker build --build-arg DB_USER=$DB_USER  --build-arg DB_PASS=$DB_PASS --build-arg DB_HOST=$DB_HOST -t filip505/mynode:latest ./server

     # deploy the image
     - run: docker push filip505/mynode:latest

     - run: |
        brew update
        brew install awsebcli

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build

      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # - run: |
      #     TAG=0.1.$CIRCLE_BUILD_NUM
      #     docker build -t filip505/mynode:$TAG . 
      #     docker push mynode/server:$TAG